color: null
description: null
fieldLayouts:
  51e4c283-262e-4c73-a056-8e1e4780a7d7:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-30T10:52:41+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9541eec3-f408-4032-a6c5-01fff6eda2be
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T10:52:41+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: dfc5ce4c-aa39-4a85-9fd6-81919a96c6aa # Sector Page Builder - Accordion - Accordion Content
            handle: null
            instructions: null
            label: 'Accordion Content'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7bc24910-a273-406c-90c5-81a6f7ed0e42
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3958c91b-74c5-4dae-92dc-eda7974af0f7
        userCondition: null
handle: accordion
hasTitleField: false
icon: null
name: Accordion
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
