color: null
description: null
fieldLayouts:
  02a8da32-1dc8-407e-a88f-bbb497e7294f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c96e6c65-f91b-43a9-9fb8-224c0b75043e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 8b71b520-8834-4f29-b0be-6aef0f288e42 # Article Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aee42657-fd63-4326-aeb3-0fa621b49172
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 70d46e89-cdf4-4e82-98ee-00455d039d33 # Article Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39156912-56ed-4497-a829-80e0afb4a780
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 32aae13b-0771-4032-80b3-9e5a57d78829
        userCondition: null
handle: articles_sectionItems
hasTitleField: true
icon: null
name: 'New Article'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
