color: null
description: null
fieldLayouts:
  8346da5d-b2a3-49cf-a8d6-7e71db4abea4:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-17T13:16:56+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c82c4f42-7102-4a19-b0ee-2d31bd4c9a70
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T15:53:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0392e2de-2bdb-4e50-ba2c-0a715e112283 # Sector Page Builder - Info Blocks - Blocks - Block Image
            handle: heroImage
            instructions: null
            label: 'Hero Image'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 558ea6d1-8604-4eb6-8537-7e0b5e6a7551
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-09-17T15:53:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aea2570e-71e8-49d8-bf72-d4c2bb30ce4b # Plain Text
            handle: heroTitle
            instructions: null
            label: 'Hero Title'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58d7d0e0-b574-40e8-998b-9357b2252f51
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-09-17T15:53:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aea2570e-71e8-49d8-bf72-d4c2bb30ce4b # Plain Text
            handle: heroText
            instructions: null
            label: 'Hero Text'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5fabaff-e1d7-4bed-9f59-35f04a5ec156
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-17T15:53:26+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 19a8c919-b8e3-4222-861c-449cc2e0c445
            userCondition: null
          -
            dateAdded: '2024-09-17T16:00:40+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aea2570e-71e8-49d8-bf72-d4c2bb30ce4b # Plain Text
            handle: introHeader
            instructions: null
            label: 'Intro Header'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 779be01b-fd50-4c6d-a905-bc50887b48ad
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T13:23:23+00:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Jobs are automatically pulled through once created'
            type: craft\fieldlayoutelements\Tip
            uid: 682b0cbe-e037-489f-912c-1774faf87dc4
            userCondition: null
        name: Content
        uid: 3a419160-e10b-4cc7-9d5c-e4a94088bf36
        userCondition: null
handle: careers_sectionIntroPage
hasTitleField: false
icon: null
name: 'Careers Landing'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{heroTitle}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
