color: null
description: null
fieldLayouts:
  2034892c-8338-46e2-aff4-9a0bd40b1579:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-09T15:17:52+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: 'Product Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 754ea9cc-7a3a-4cbf-a9ac-e1886de6c641
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-09T15:31:10+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4ed1b04a-6530-4a34-874c-c5f29f911e66 # Four Images
            handle: productImages
            instructions: 'You can add up to 4 images'
            label: 'Product Images'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f16596c-70c9-4095-910a-f32f7e3522b9
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-10-09T15:20:57+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 10dcb136-b8a7-4325-90fe-c0cda2e1ebd1 # Simple Text
            handle: productDescription
            instructions: null
            label: 'Product Description'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89282e95-bf80-44f6-ad7f-326c08926bab
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-10-09T15:20:57+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 54ad6db4-d4f1-442d-b6c6-c1b6ac754cf9 # Straight Text
            handle: null
            instructions: null
            label: 'Product Price'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 88212cc4-9dc5-4e16-ba3b-2f5487a08c1b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b8f80f4e-bc8e-4fde-9258-2892cfbce73f
        userCondition: null
handle: ent_productList
hasTitleField: true
icon: null
name: 'Product List'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
