color: purple
description: null
fieldLayouts:
  47e6eaef-b74e-45c4-b5ec-0f4bc10eb784:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:b61bf591-76e4-4068-bd54-cf8a11ed496d'
      - 'layoutElement:a002485b-6b34-4f64-9681-b48ec473cade'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-14T16:22:53+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: Name
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5017b916-5478-4247-b52b-2dc60c35c888
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-07-14T16:26:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 54ad6db4-d4f1-442d-b6c6-c1b6ac754cf9 # Straight Text
            handle: position
            instructions: null
            label: Position
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b61bf591-76e4-4068-bd54-cf8a11ed496d
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-07-14T16:26:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 04ddff7f-52ed-458a-bc0c-a3a9d4b76f4d # Single Image
            handle: staffPhoto
            instructions: null
            label: Photo
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a002485b-6b34-4f64-9681-b48ec473cade
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-07-14T16:26:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 10dcb136-b8a7-4325-90fe-c0cda2e1ebd1 # Simple Text
            handle: shortBio
            instructions: null
            label: 'Short Bio'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7b604251-5c83-477c-98a3-1148494e0d26
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-07-14T16:27:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c1e5720b-386a-4bba-8784-306bc80ba4f6 # Specialities
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fdd05f4f-b125-4094-95a9-8cd20e626ea3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-15T12:53:54+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b7f863e4-f418-4417-9cb5-c6d3f5bf1155 # Can be booked?
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: be51c651-1817-460e-b798-ef154f7722f1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4fc40701-f152-43fc-bff2-691f08719937
        userCondition: null
handle: ent_team
hasTitleField: true
icon: null
name: Team
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
