color: orange
description: null
fieldLayouts:
  87fd23c3-108c-44a0-847e-51e36549d20c:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:cc662441-b460-4205-ba9b-b8693c33178c'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-17T13:46:12+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d22dd4d3-0cb9-4384-a58b-59fae0e82d8f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T13:46:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aea2570e-71e8-49d8-bf72-d4c2bb30ce4b # Plain Text
            handle: blockTitle
            instructions: null
            label: 'Block Title'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc662441-b460-4205-ba9b-b8693c33178c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T13:46:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cbaf71b5-75c1-4593-9f45-4113e7c5207e # Information Blocks - Information Block - Block Text
            handle: null
            instructions: null
            label: 'Block Text'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b57e24b-59e9-4e46-9cbf-226769c15252
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T13:46:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0e0bd4a6-557e-4137-a6fc-789aa94d3753 # Information Blocks - Information Block - Block Points
            handle: null
            instructions: null
            label: 'Block Points'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f3385975-f0b2-41b1-b75e-481fe3d349fe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T13:46:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1b5f0de8-2a1b-4344-b572-b5e16c422e70 # Information Blocks - Information Block - Block Image
            handle: null
            instructions: null
            label: 'Block Image'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e46da14-5181-41c8-9c6c-bb09875c2d83
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-09-17T13:46:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7df641c4-625f-400f-9821-424be06f8fd7 # Information Blocks - Information Block - Block Colour
            handle: null
            instructions: null
            label: 'Block Colour'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc97a675-680a-48e4-b9cd-35a9432ee86a
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2024-09-17T13:46:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 691fe8b2-901b-4483-800d-f958db3ba998 # Information Blocks - Information Block - Block Link
            handle: null
            instructions: null
            label: 'Block Link'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b78765ba-6e89-4e0e-8ef4-237e906752b9
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 01109ebe-3dea-48cf-8e6b-06853888bf97
        userCondition: null
    thumbFieldKey: 'layoutElement:0e46da14-5181-41c8-9c6c-bb09875c2d83'
handle: informationBlock
hasTitleField: false
icon: cabinet-filing
name: 'Information Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
