color: null
description: null
fieldLayouts:
  ec3dd3d9-a4b6-4861-b20d-a5aef2cb1a6c:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:9c22340b-253a-4e58-9b53-489db0691168'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-17T13:46:12+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f3b9e280-cbe8-4486-a539-b7e0de48e919
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T13:46:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aea2570e-71e8-49d8-bf72-d4c2bb30ce4b # Plain Text
            handle: blockTitle
            instructions: null
            label: 'Block Title'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c22340b-253a-4e58-9b53-489db0691168
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T13:46:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f028fab8-86ea-4a6d-a9ee-5aa62b806de9 # Sector Page Builder - Info Blocks - Blocks - Block Text
            handle: blockText
            instructions: null
            label: 'Block Text'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c5427f7-b955-4d7a-ac2e-a6bce3c888d7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T13:46:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0392e2de-2bdb-4e50-ba2c-0a715e112283 # Sector Page Builder - Info Blocks - Blocks - Block Image
            handle: blockImage
            instructions: null
            label: 'Block Image'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2d5deb1-75d5-439b-8069-9b48b2e4b079
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e02ac34d-2338-4ab4-8ef2-d53855cc9503
        userCondition: null
    thumbFieldKey: 'layoutElement:c2d5deb1-75d5-439b-8069-9b48b2e4b079'
handle: infoBlockBlock
hasTitleField: false
icon: null
name: 'Sector Page Builder - Info Blocks - Blocks Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
