color: null
description: null
fieldLayouts:
  9cb917ca-e552-464b-9232-c1cf6d0a8cca:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: f53d0986-7780-467d-af7d-285af1620e61 # Sector Page Builder - Info Blocks - Blocks
            handle: null
            instructions: null
            label: Blocks
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 265f5d1b-7cb1-461a-8338-20a451df0762
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6cec3bdb-7111-400d-b754-85c3ca5a3d11
        userCondition: null
handle: infoBlocks
hasTitleField: false
icon: null
name: 'Info Blocks'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
