color: null
description: null
fieldLayouts:
  d749d216-fedf-4832-bef5-bfab1d82b8b9:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-10-09T13:51:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 75d5ff91-e0e7-479a-b047-041d2c3e1649 # Page Header
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c6ef72e-4934-4888-adc0-52e9485e3b30
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-09T15:22:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9f2c1146-2e6e-476c-9e77-c6e736164ed7 # Brands and Products
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 027c0126-efde-4dff-9b4b-2c7ddb03bff2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-10T08:52:30+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 04ddff7f-52ed-458a-bc0c-a3a9d4b76f4d # Single Image
            handle: genericImage
            includeInCards: false
            instructions: "This will appear wherever you don't include an image with a product."
            label: 'Generic Placeholder Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99000363-d77e-47b7-9946-f7f8bf2084e9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-09T13:52:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 71202746-fb78-4408-b9b3-1c3d1e39ffb8 # Call to Action
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a102bde0-1dd1-4364-b410-a59b0b73ba92
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 85ade5c6-fbdd-4faa-b988-7c0541e8e56e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-11-10T14:28:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f425b0e8-1203-40a7-9f6f-108688342507 # SEO Information
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57b45dd1-10bb-4516-afa2-1e9dd7ca5015
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 31c30712-2e7f-4388-9752-a567dc24e090
        userCondition: null
handle: page_ent_products
hasTitleField: false
icon: null
name: Products
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: Products
titleTranslationKeyFormat: null
titleTranslationMethod: site
