color: fuchsia
description: null
fieldLayouts:
  a2ebd040-5488-4a65-8975-65ffc92009c5:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:bd0e9098-173c-465c-962e-b1d3570dc5df'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-17T13:46:13+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 152d2aa3-dad2-4110-90b8-8f692df4ba6e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T13:46:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aea2570e-71e8-49d8-bf72-d4c2bb30ce4b # Plain Text
            handle: sector
            instructions: null
            label: Sector
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd0e9098-173c-465c-962e-b1d3570dc5df
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T13:46:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 357ccac9-a71d-4aac-b2b5-99d93e47140b # Sectors - Link to page
            handle: linkToPage
            instructions: null
            label: 'Link to page'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 80a954fe-cfcf-45aa-8a32-83568eba1114
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c961491e-ce49-441c-896c-ea95289013b8
        userCondition: null
handle: sectorsBlock
hasTitleField: false
icon: null
name: 'Sectors Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
