color: null
description: null
fieldLayouts:
  94f32c6c-b432-4850-bb15-3a2578cd9e2f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-17T13:45:28+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 073facdb-76d9-45d6-b0d0-994152746fb9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T13:45:28+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 7b786651-6165-43c1-9716-8a7287b7333a
            userCondition: null
          -
            dateAdded: '2024-09-17T13:45:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0392e2de-2bdb-4e50-ba2c-0a715e112283 # Sector Page Builder - Info Blocks - Blocks - Block Image
            handle: heroImage
            instructions: null
            label: 'Hero Image'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ee47390-9dc3-4d8a-824f-d24b8b97bcbf
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-17T13:45:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aea2570e-71e8-49d8-bf72-d4c2bb30ce4b # Plain Text
            handle: heroTitle
            instructions: null
            label: 'Hero Title'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02c767a1-5200-41a9-a0f7-b197ec45683c
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-17T13:45:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aea2570e-71e8-49d8-bf72-d4c2bb30ce4b # Plain Text
            handle: heroText
            instructions: null
            label: 'Hero Text'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82ea7f08-74e2-4fa2-9f16-470c705d769d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6d6f04d0-cafc-4257-b08a-bd30016028e5
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-23T13:17:18+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 97c83234-c29d-4007-9c40-ad6c54a1cfb6
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca6686bb-7756-45b1-818e-63f624c4308f
            userCondition: null
            warning: null
            width: 100
        name: 'SEO Information'
        uid: f24e9996-0b0f-4699-8449-47e63f3956cc
        userCondition: null
handle: services_sectionIntroPage
hasTitleField: true
icon: null
name: 'Services - Overview Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
