color: green
description: null
fieldLayouts:
  3ed48936-4097-48b5-93f8-dc785f866158:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:b9ffcb40-cc10-4bd4-ab4e-4a50687d1e11'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7012a503-e29d-4417-abfe-980928e9f76a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 45a77e80-e4f5-4778-8d99-bf26d0758633 # Testimonials - Quote
            handle: null
            instructions: null
            label: Quote
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9ffcb40-cc10-4bd4-ab4e-4a50687d1e11
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            fieldUid: 491bb95f-d9b6-432e-9c22-2b166d5e49bf # Testimonials - Person
            handle: null
            instructions: null
            label: Person
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: debcec87-6a34-4546-90ed-ff13f863a446
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 520cd8c2-1411-4f2e-956d-9beb895b8b7f
        userCondition: null
handle: testimonialsBlock
hasTitleField: false
icon: thumbs-up
name: 'Testimonials Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
