color: null
description: null
fieldLayouts:
  71595cb5-1ab5-4f7e-9871-b89c97dbddee:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-27T13:06:24+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: 'Sub Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8881b1b2-3123-40bd-a830-3080030589cb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-27T13:09:59+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 70d46e89-cdf4-4e82-98ee-00455d039d33 # Article Text
            handle: fd_text
            instructions: null
            label: Text
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5a9493ba-82b4-44db-8b79-3d78f1016f3f
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-27T13:09:59+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8b71b520-8834-4f29-b0be-6aef0f288e42 # Article Image
            handle: null
            instructions: 'Image is NOT mandatory'
            label: 'Supporting Image'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce3e6cfa-23f7-4444-8f16-c230c6b261b5
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: decf9b37-4971-47c4-8a6a-89cce3752fad
        userCondition: null
handle: textImage
hasTitleField: true
icon: null
name: 'Text / Image'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
