color: null
description: null
fieldLayouts:
  43072aab-0052-4f3b-808d-a60fda551313:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-17T13:45:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c4820f23-27e0-47ec-8c97-f33756bff075
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T13:45:29+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 0fdff916-02ad-40ed-8157-6f41b1647a6f
            userCondition: null
          -
            dateAdded: '2024-09-17T13:45:29+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0392e2de-2bdb-4e50-ba2c-0a715e112283 # Sector Page Builder - Info Blocks - Blocks - Block Image
            handle: heroImage
            instructions: null
            label: 'Hero Image'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5bc1ff31-6170-4fee-aebb-1dbc9319901c
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-17T13:45:29+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aea2570e-71e8-49d8-bf72-d4c2bb30ce4b # Plain Text
            handle: heroTitle
            instructions: null
            label: 'Hero Title'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 178bb543-bb4f-4288-9325-60f9ede9ed09
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-17T13:45:29+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aea2570e-71e8-49d8-bf72-d4c2bb30ce4b # Plain Text
            handle: heroText
            instructions: null
            label: 'Hero Text'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 32be4466-194b-4367-bbc9-5ce65ee51bc0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T13:45:29+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 6494642a-53f6-4e66-befe-05bced844b4c
            userCondition: null
          -
            dateAdded: '2024-09-17T13:45:29+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 828d697f-6d07-4af1-9b83-fef2467ee74d # Text Block
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7164fa66-3477-4d3b-87c4-bad3958881ce
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T13:45:29+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: eabefd6e-c904-4f55-9caa-f3fb9bedd04a
            userCondition: null
          -
            dateAdded: '2024-09-17T13:45:29+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 45a8bbed-1edd-4c3e-a925-95ea582c86bd # Information Blocks
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 11fd3f92-92b3-40d1-b00b-7cf3dbc0156e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T13:45:29+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 6f6acad5-c4bf-47be-88ff-15f3b77c446b
            userCondition: null
          -
            dateAdded: '2024-09-17T13:45:29+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: af51211b-76af-4f5e-a5a0-478a6bf4ae54 # Full Width Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5fb1b750-fbfb-42a5-a98e-2d82fa294146
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3e5661bf-cc5d-4550-b89f-241ffea8de93
        userCondition: null
handle: whyUs
hasTitleField: true
icon: null
name: 'Why Us'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
