baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-GB
name: 'Altius Lifts'
primary: true
siteGroup: 87f5b40a-7044-4f5f-afdf-1c5049bd622c # Caledonian Lifts
sortOrder: 1
