altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  4ca0de71-7b77-40b3-9091-3f63929ef04c:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-18T13:25:47+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 3cd74b7b-5ddb-4ab7-8899-a1e74b0e8792
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4217bfda-e8b8-4278-840b-926d02531ecf
        userCondition: null
fs: cvs
handle: cvs
name: "CV's"
sortOrder: 3
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
