altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  70016bb0-3b7f-44f3-9274-41a948e462a8:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 8cddb836-5ad6-4a28-b12e-a71c93f0bc20
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1549fbbe-8f8f-46b4-8903-fb1592f85e03
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: /transforms
