columnSuffix: null
handle: canBeBooked
instructions: "Determines whether the 'Book Now' button is shown."
name: 'Can be booked?'
searchable: false
settings:
  default: true
  offLabel: 'No'
  onLabel: 'Yes'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
