columnSuffix: null
handle: cb_pageHeader
instructions: null
name: 'Page Header'
searchable: false
settings:
  fieldLayouts:
    __assoc__:
      -
        - 5d3bc16a-0a1c-4c37-8e73-4de24707cd95
        -
          __assoc__:
            0:
              - tabs
              -
                -
                  __assoc__:
                    0:
                      - name
                      - Content
                    1:
                      - uid
                      - 45a11df1-738c-405d-b6a6-9fa1ef311120
                    4:
                      - elements
                      -
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            1:
                              - handle
                              - pageTitle
                            2:
                              - label
                              - 'Page Title'
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 100
                            10:
                              - dateAdded
                              - '2025-07-09T09:08:26+00:00'
                            11:
                              - uid
                              - 5794b33a-9aeb-415a-86ac-186366dc9e2a
                            14:
                              - fieldUid
                              - 54ad6db4-d4f1-442d-b6c6-c1b6ac754cf9 # Straight Text
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            1:
                              - handle
                              - subHeading
                            2:
                              - label
                              - 'Sub Heading'
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 100
                            10:
                              - dateAdded
                              - '2025-07-09T09:08:26+00:00'
                            11:
                              - uid
                              - da309fa1-70bd-497e-b18e-08c2f5fcf4ff
                            14:
                              - fieldUid
                              - 54ad6db4-d4f1-442d-b6c6-c1b6ac754cf9 # Straight Text
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            1:
                              - handle
                              - promoLink
                            2:
                              - label
                              - 'Promo Link'
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 100
                            10:
                              - dateAdded
                              - '2025-07-30T09:08:07+00:00'
                            11:
                              - uid
                              - cd2fa102-6ed6-4015-b18e-cf2f19a28db9
                            14:
                              - fieldUid
                              - 54b32803-64e0-46aa-bacf-ecddf2f5db7a # Section Link
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            1:
                              - handle
                              - buttonIcon
                            2:
                              - label
                              - 'Button Icon'
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 50
                            10:
                              - dateAdded
                              - '2025-07-31T08:47:38+00:00'
                            11:
                              - uid
                              - 844828e3-2790-46dc-ae12-1d8d18f4f6b9
                            14:
                              - fieldUid
                              - 54ad6db4-d4f1-442d-b6c6-c1b6ac754cf9 # Straight Text
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            1:
                              - handle
                              - buttonClass
                            2:
                              - label
                              - 'Button Class'
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 50
                            10:
                              - dateAdded
                              - '2025-07-31T08:49:43+00:00'
                            11:
                              - uid
                              - 83060951-7a84-4ae6-a476-b8cc49962190
                            14:
                              - fieldUid
                              - 54ad6db4-d4f1-442d-b6c6-c1b6ac754cf9 # Straight Text
            3:
              - cardThumbAlignment
              - end
  viewMode: pane
translationKeyFormat: null
translationMethod: site
type: craft\fields\ContentBlock
