columnSuffix: null
handle: fd_availability
instructions: null
name: Hours
searchable: false
settings:
  addRowLabel: 'Add an option'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - 'Days / Hours'
            -
              - handle
              - availability
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
