columnSuffix: null
handle: fd_criteria
instructions: null
name: Criteria
searchable: false
settings:
  addRowLabel: 'Add Criteria'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Criteria
            -
              - handle
              - criteria
            -
              - width
              - ''
            -
              - type
              - multiline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
