columnSuffix: null
handle: fd_hours
instructions: null
name: Hours
searchable: false
settings:
  addRowLabel: 'Add Schedule'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - 'Add Days/Hours etc...'
            -
              - handle
              - addDaysHoursEtc
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
