columnSuffix: null
handle: fd_jobBenefits
instructions: null
name: 'Job Benefits'
searchable: false
settings:
  addRowLabel: 'Add a benefit'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Benefit
            -
              - handle
              - benefit
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
