columnSuffix: null
handle: mx_faqs
instructions: null
name: FAQs
searchable: false
settings:
  createButtonLabel: 'New FAQ'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 4ff89192-ffa3-4fc7-99fc-9714ea2c8bc7 # FAQs
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
