columnSuffix: null
handle: mx_sectionIntroduction
instructions: null
name: 'Section Introduction'
searchable: false
settings:
  createButtonLabel: 'Add Intro'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 1c4d6320-4d2d-4112-bd71-b4e2cd5c7860 # Section Intro
  includeTableView: false
  maxEntries: 1
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
