columnSuffix: cwqlqwzu
handle: person
instructions: null
name: 'Testimonials - Person'
searchable: false
settings:
  addRowLabel: 'Add a row'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Name
            -
              - handle
              - name
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - Company
            -
              - handle
              - company
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - col2
          - ''
  maxRows: null
  minRows: null
  staticRows: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
