dateModified: 1765536066
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - dateCreated
        - desc
      defaultViewMode: ''
      disabled: false
      key: singles
      tableAttributes:
        - status
        - link
      type: native
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:e5168587-7fe8-40c8-86c9-f416b40ac41e' # News
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: '*'
      tableAttributes:
        - status
        - section
        - postDate
        - expiryDate
        - link
      type: native
email:
  fromEmail: access@hypha.media
  fromName: TLE-2025
  transportType: craft\mail\transportadapters\Sendmail
fs:
  assets:
    hasUrls: true
    name: Assets
    settings:
      path: assets
    type: craft\fs\Local
    url: /assets
graphql:
  publicToken:
    enabled: false
    expiryDate: null
meta:
  __names__:
    0af69162-000c-4bb3-a42e-77f5a08558e3: Phone # Phone
    0f026b4b-1c4d-43fd-9071-50babbe0d30d: 'Services Section' # Services Section
    2bc6cf54-0be9-41dd-950d-f337f8afa9ce: 'Opening Hours' # Opening Hours
    2fa578a2-b3ab-4fef-8fb9-2e9b9145a907: Contact # Contact
    3b0f3bfb-1b7f-4be0-94f0-0a2f29509f4f: Team # Team
    3b68cd98-cd43-4ae2-8d02-61222bda35ba: 'Cards Section' # Cards Section
    3b3650a6-7e79-4860-9537-41787a90b09b: Services # Services
    03bf5298-bb72-48f2-8fca-8d37faf4a83f: 'Sub Services' # Sub Services
    3e7a3e99-ba2f-44b4-966e-e6783dd7e3c1: 'Hero Buttons' # Hero Buttons
    3fcb9a5b-a541-4879-a645-a21fa6bac7ca: 'Job Descriptions' # Job Descriptions
    04ddff7f-52ed-458a-bc0c-a3a9d4b76f4d: 'Single Image' # Single Image
    4ed1b04a-6530-4a34-874c-c5f29f911e66: 'Four Images' # Four Images
    5c61d44f-616f-4ae5-b273-cdb67ecfff52: Connect # Connect
    5c8228fd-b7e4-4fa8-b9dd-2a5389c4bb6c: 'Homepage Hero' # Homepage Hero
    5d6f4599-0482-49dc-b4e6-eb7db8af869d: 'Basic with H2' # Basic with H2
    5de5baa5-50e4-4208-a69b-3036b56bfa6e: Careers # Careers
    5edfc78e-63a4-4023-8fba-f4818a8e32a0: news-article # news-article
    5f596b25-ec1e-469a-8c81-e040276faa25: 'Offer Cards' # Offer Cards
    6b2d5a14-d767-4360-88fa-ca10896170a4: 'Promo Links' # Promo Links
    6d8f0d59-dcb0-4d1c-b7fc-1847d203b478: Colour # Colour
    7cc8b97c-23a2-4e4d-ae9e-59a1b66582f6: Services # Services
    7e163a5f-8874-4292-a7d9-ecbcc6e308d2: 'Sub Services' # Sub Services
    8dc06e17-b136-4714-997a-6b1f293e9c41: 'Bold, Italic and Link' # Bold, Italic and Link
    8eed41b9-47a1-4b42-8361-6e2f9dd27c9f: 'Social Links' # Social Links
    9ab1b041-ae5f-451c-aa7a-e7dda1e2d1f9: 'Title Field' # Title Field
    9b42751e-b87f-4957-8c54-5a457d443a7f: 'Basic with H2' # Basic with H2
    9f2c1146-2e6e-476c-9e77-c6e736164ed7: 'Brands and Products' # Brands and Products
    10dcb136-b8a7-4325-90fe-c0cda2e1ebd1: 'Simple Text' # Simple Text
    21f4ef74-64dc-48e3-bb94-93d62c25ef08: 'Hair Haven' # Hair Haven
    24b60046-c604-467a-9159-5c28626085cb: FAQs # FAQs
    30d70629-c8e5-40db-9f27-dd7dd53d0afb: 'Card Link' # Card Link
    35f4bfc2-4432-43df-bd81-7ccfd0e7a7f1: Team # Team
    43d74a4b-22f2-481f-9e51-582bfd8ccd86: Times # Times
    43ebf591-142c-4702-86cf-9a605575688a: 'Brands and Products' # Brands and Products
    45b3edbc-893f-4d31-acaa-4f187ee99099: Cards # Cards
    48ff7023-466f-423c-a293-c4ebec9ab0a4: Testimonials # Testimonials
    54ad6db4-d4f1-442d-b6c6-c1b6ac754cf9: 'Straight Text' # Straight Text
    54b32803-64e0-46aa-bacf-ecddf2f5db7a: 'Section Link' # Section Link
    69b12cc6-3150-4b5d-9318-88d440f5431e: Location # Location
    69d4f867-81b3-416a-b6d1-35d2428bf5dd: Contact # Contact
    70cbf51f-c6a4-4501-ab10-6544b0adb9fd: Simple # Simple
    75d5ff91-e0e7-479a-b047-041d2c3e1649: 'Page Header' # Page Header
    80f72898-9dbf-499d-8f33-abd3d52e8a3e: 'Range Text Left or Right' # Range Text Left or Right
    91bf7b22-c506-4a80-8c0d-506bf77a3dfc: Services # Services
    172c19a6-5e5c-49fc-b221-96f628e74fbe: 'Frequently Asked Questions' # Frequently Asked Questions
    223fbc1e-4eb0-4383-82ba-1041ce5b1e00: Homepage # Homepage
    00293d02-a8ce-4397-916e-d550809b272d: Offers # Offers
    392d336a-d1e6-4233-89d7-cf232f91adb8: 'Bold and Italic' # Bold and Italic
    552cbd7b-3ff5-4b3a-8908-5c1582c42161: Offers # Offers
    678e5f0a-719b-48e9-85b7-506679f364f5: Homepage # Homepage
    784bb5e4-8286-4b99-85c7-5bdf3d014a6d: 'Current Opportunities' # Current Opportunities
    3815c76e-4a12-40f8-8dd1-9568da8fdf25: Team # Team
    4347ac84-9083-43b9-b2e9-eab3eefcfb45: 'Job Type' # Job Type
    9319c08a-bbe3-4e7a-9f29-6e0caa7c1433: 'Offer T&Cs' # Offer T&Cs
    9832c994-1873-429f-b552-652988c0558b: Salon # Salon
    046080fc-7aad-4c07-b0fa-b55961a0f0de: Salon # Salon
    55300cfe-bdf4-4ff4-8cb4-41e6c4d57622: 'Service Type' # Service Type
    68525dcd-7e0b-4ad5-b369-8366276b3c96: 'Product List' # Product List
    88590e6e-50fb-4242-94c5-5cdabdb88f86: 'Job Descriptions' # Job Descriptions
    224318bf-f739-48f8-b570-dc4deefe6f0e: Testimonials # Testimonials
    26138429-fcf3-4e89-a520-7bfdbd1591ee: Assets # Assets
    43665714-2299-44fa-abf3-97b45c8a12c7: 'Services Cards' # Services Cards
    56786631-8fc8-4a52-8c4c-4655bc9bba07: Products # Products
    71202746-fb78-4408-b9b3-1c3d1e39ffb8: 'Call to Action' # Call to Action
    a0d638c3-37dd-42c0-bcdc-25e945644b12: Email # Email
    a6966eba-abc7-43bd-aad8-95073f426a6d: 'Summary Section' # Summary Section
    b7f863e4-f418-4417-9cb5-c6d3f5bf1155: 'Can be booked?' # Can be booked?
    b8de7878-afc8-4f97-8281-a4b2d990dee4: Responsibilities # Responsibilities
    b79b4e43-e6c0-4c44-9a15-f07ccdaa5d37: 'Products Section' # Products Section
    b393e30c-26ec-4a72-b5f9-806b61952f7e: Products # Products
    b2608e5b-6a78-41bb-b819-04900f98ce1a: 'Social Section' # Social Section
    b5144bca-43e4-4a75-8d36-4405e3f2629a: 'Testimonial Text' # Testimonial Text
    b42073cc-57b6-4636-b08c-5b9bb29facb4: 'Sub Service Intro' # Sub Service Intro
    b3726252-6c72-46e5-b01e-d92574299019: 'Single Button' # Single Button
    c1e5720b-386a-4bba-8784-306bc80ba4f6: Specialities # Specialities
    c4bebee5-c1d4-47bf-be47-8bcfeb2783ec: 'Services Cards' # Services Cards
    c7b16797-a8aa-4497-8ac7-7154e48333bd: Products # Products
    c55dc4be-da97-4592-9d58-444951e11eef: Team # Team
    c56a99f0-e8f2-4e89-916d-b5c034c8bed1: 'Offer Cards' # Offer Cards
    c969543d-de4c-4d09-9576-8758dc27afd1: 'Testimonials Section' # Testimonials Section
    cd54e7f4-5c22-4c1f-97e1-6e017ee1fcc6: 'Sub Services' # Sub Services
    d2c3b28c-ed81-4d1d-a2c8-8a4cfff51ecd: 'Price List' # Price List
    d2f55de7-1c60-480a-99db-3d871461fe31: 'Text Color' # Text Color
    d51d5a9b-69fe-4e13-acd6-d4f9a20ccae1: 'Title Text' # Title Text
    d60136f4-9baf-4f3c-9a20-bbd1bf47b28a: Services # Services
    d9707244-1d4e-4b5b-9d06-b6055492603e: 'Hair Haven' # Hair Haven
    da000afe-cb2f-43bf-a97b-769110bde6f6: 'Sub Services' # Sub Services
    dfb73ee5-ea53-4d09-85e2-8ec1dc827d28: News # News
    e2c6ec4d-d46c-47ec-800d-206eea4d27b1: 'Contact Form' # Contact Form
    e7d1aee4-6d2a-4c14-b96d-33b111833a0b: Services # Services
    e72fbf57-838b-4a23-af94-8aba3641a43c: Requirements # Requirements
    e21536ab-798f-4de7-9666-70903d331159: Services # Services
    e5168587-7fe8-40c8-86c9-f416b40ac41e: News # News
    eb38d150-0774-403c-8be3-6b8c480c6f8e: Specialities # Specialities
    eb143e66-f41e-413f-aaff-b1cc34d3e545: 'Simple Cards' # Simple Cards
    ef5e44d9-0d4b-4d70-9107-c660a781fc10: Careers # Careers
    f0eb6556-1429-4336-86ff-322eb5be4254: 'Intro Section' # Intro Section
    f63cfe62-8af4-48a8-91a3-aab84680d3b6: 'Featured Article?' # Featured Article?
    f117f59d-5600-46e1-8a81-3dec61d0f0c9: 'Six Images' # Six Images
    f425b0e8-1203-40a7-9f6f-108688342507: 'SEO Information' # SEO Information
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  cloner:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      allowedMessageFields: null
      prependSender: 'On behalf of'
      prependSubject: 'New message from TLE-2025'
      successFlashMessage: 'Your message has been sent.'
      toEmail: martin@hypha.media
  entry-level:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      sectionConfig:
        __assoc__:
          -
            - e5168587-7fe8-40c8-86c9-f416b40ac41e # News
            -
              __assoc__:
                -
                  - typeHierarchy
                  -
                    __assoc__:
                      -
                        - dfb73ee5-ea53-4d09-85e2-8ec1dc827d28 # News
                        -
                          __assoc__:
                            -
                              - parentTypeUid
                              - ''
                      -
                        - 5edfc78e-63a4-4023-8fba-f4818a8e32a0 # news-article
                        -
                          __assoc__:
                            -
                              - parentTypeUid
                              - dfb73ee5-ea53-4d09-85e2-8ec1dc827d28 # News
                -
                  - typeOrder
                  -
                    - dfb73ee5-ea53-4d09-85e2-8ec1dc827d28 # News
                    - 5edfc78e-63a4-4023-8fba-f4818a8e32a0 # news-article
  field-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  freeform:
    edition: express
    enabled: true
    schemaVersion: 5.6.2
  obfuscator:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: 55JPLHLCDK5V239ZG7MJ1967
    schemaVersion: 3.0.13
    settings:
      addHrefLang: true
      addPaginatedHreflang: true
      addXDefaultHrefLang: true
      alwaysIncludeCanonicalUrls: false
      cpTitlePrefix: 'âš™ '
      cspNonce: ''
      cspScriptSrcPolicies:
        -
          __assoc__:
            -
              - policy
              - "'self'"
      devModeCpTitlePrefix: 'ðŸš§âš™ '
      devModeTitlePrefix: 'ðŸš§ '
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      enableDebugToolbarPanel: true
      enableJsonLdEndpoint: false
      enableMetaContainerEndpoint: false
      enableSeoFileLinkEndpoint: false
      environment: dev
      excludeNonCanonicalUrls: false
      generatorEnabled: true
      headersEnabled: true
      includeHomepageInBreadcrumbs: true
      lowercaseCanonicalUrl: true
      manuallySetEnvironment: false
      maxDescriptionLength: 155
      maxTitleLength: 70
      metaCacheDuration: 0
      pluginName: SEOmatic
      regenerateSitemapsAutomatically: true
      renderEnabled: true
      separatorChar: '|'
      sidebarDisplayPreviewTypes:
        - google
        - twitter
        - facebook
      siteGroupsSeparate: true
      siteUrlOverride: ''
      sitemapsEnabled: true
      socialMediaPreviewTarget: true
      submitSitemaps: true
      truncateDescriptionTags: true
      truncateTitleTags: true
      xDefaultSite: 0
system:
  edition: solo
  live: true
  name: 'Hair Haven'
  retryDuration: null
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
