defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 69d4f867-81b3-416a-b6d1-35d2428bf5dd # Contact
handle: contact
maxAuthors: 1
name: Contact
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  21f4ef74-64dc-48e3-bb94-93d62c25ef08: # Hair Haven
    enabledByDefault: true
    hasUrls: true
    template: contact.twig
    uriFormat: contact
type: single
