defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 678e5f0a-719b-48e9-85b7-506679f364f5 # Homepage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  21f4ef74-64dc-48e3-bb94-93d62c25ef08: # Hair Haven
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
