defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 00293d02-a8ce-4397-916e-d550809b272d # Offers
handle: offers
maxAuthors: 1
name: Offers
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  21f4ef74-64dc-48e3-bb94-93d62c25ef08: # Hair Haven
    enabledByDefault: true
    hasUrls: true
    template: offers.twig
    uriFormat: offers
type: single
