defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 7d7b349e-bfee-48a0-8cf4-7a0eefc10c76 # Services - Overview Page
  -
    uid: 6f2dbcfd-2b90-4b8a-8fb1-f15c5d85edbe # Add a New Service
handle: services
maxAuthors: 1
name: Services
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  fe4e75c8-43fa-445f-a134-622af7819f98: # Altius Lifts
    enabledByDefault: true
    hasUrls: true
    template: _sections/services/_entry.html
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: 2
  uid: a117873a-72c9-4e88-911c-03e5a4e5c1ea
type: structure
