defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 3b0f3bfb-1b7f-4be0-94f0-0a2f29509f4f # Team
handle: team
maxAuthors: 1
name: Team
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  21f4ef74-64dc-48e3-bb94-93d62c25ef08: # Altius Lifts
    enabledByDefault: true
    hasUrls: true
    template: team.twig
    uriFormat: meet-the-team
type: single
